version: 2
jobs:
  build:
    working_directory: /root/project
    docker:
      - image: karrlab/build:0.0.18
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - cache-v8-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - cache-v8-{{ .Branch }}-
            - cache-v8-

      - run: pip2 install -U --process-dependency-links git+https://github.com/KarrLab/pkg_utils.git#egg=pkg_utils
      - run: pip2 install -U --process-dependency-links git+https://github.com/KarrLab/karr_lab_build_utils.git#egg=karr_lab_build_utils
      - run: pip2 install -U --process-dependency-links -e .[all]
      
      - run: pip3 install -U --process-dependency-links git+https://github.com/KarrLab/pkg_utils.git#egg=pkg_utils
      - run: pip3 install -U --process-dependency-links git+https://github.com/KarrLab/karr_lab_build_utils.git#egg=karr_lab_build_utils
      - run: pip3 install -U --process-dependency-links -e .[all]
      
      - save_cache:
          key: cache-v8-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python2.7/site-packages
            - /usr/local/lib/python3.6/site-packages

      - run: |
          set +e

          karr_lab_build_utils2 run-tests --with-xunit --with-coverage
          RESULT_PY2=$?

          karr_lab_build_utils3 run-tests --with-xunit --with-coverage
          RESULT_PY3=$?

          karr_lab_build_utils3 do-post-test-tasks
          RESULT_POST_TASKS=$?

          if [[ $RESULT_PY2 -eq 0 && $RESULT_PY3 -eq 0 && $RESULT_POST_TASKS -eq 0 ]]; then
            exit 0
          else
            exit 1
          fi

      - store_test_results:
          path: /root/project/tests/reports
      - store_artifacts:
          path: /root/project/.coverage.2.7.14
          destination: .coverage.2.7.14
      - store_artifacts:
          path: /root/project/.coverage.3.6.3
          destination: .coverage.3.6.3
      - store_artifacts:
          path: /root/project/docs/_build/html
          destination: docs
