version: 2
jobs:
  build:
    working_directory: /root/project
    docker:
      - image: karrlab/build:0.0.7
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - cache-v7-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - cache-v7-{{ .Branch }}-
            - cache-v7-

      - run: pip2 install -e .
      - run: pip2 install -U -e git+https://github.com/KarrLab/Karr-Lab-build-utils.git#egg=Karr-Lab-build-utils
      - run: karr-lab-build-utils-2 install-requirements

      - run: pip3 install -e .
      - run: pip3 install -U -e git+https://github.com/KarrLab/Karr-Lab-build-utils.git#egg=Karr-Lab-build-utils
      - run: karr-lab-build-utils-3 install-requirements
      
      - save_cache:
          key: cache-v7-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python2.7/site-packages
            - /usr/local/lib/python3.6/site-packages

      - run: |
          set +e

          pip2 install -e git+https://github.com/KarrLab/Karr-Lab-build-utils.git#egg=Karr-Lab-build-utils
          RESULT=$?
          if [ $RESULT -ne 0 ]; then
            exit $RESULT
          fi
          karr-lab-build-utils-2 run-tests tests --with-xunit --with-coverage
          RESULT2=$?

          pip3 install -e git+https://github.com/KarrLab/Karr-Lab-build-utils.git#egg=Karr-Lab-build-utils
          RESULT=$?
          if [ $RESULT -ne 0 ]; then
            exit $RESULT
          fi
          karr-lab-build-utils-3 run-tests tests --with-xunit --with-coverage
          RESULT3=$?

          karr-lab-build-utils make-and-archive-reports

          if [[ $RESULT2 -eq 0 && $RESULT3 -eq 0 ]]; then
            exit 0
          else
            exit 1
          fi

      - store_test_results:
          path: /root/project/tests/reports
      - store_artifacts:
          path: /root/project/.coverage.2.7.14
          destination: .coverage.2.7.14
      - store_artifacts:
          path: /root/project/.coverage.3.6.3
          destination: .coverage.3.6.3
      - store_artifacts:
          path: /root/project/docs/_build/html
          destination: docs
